"""empty message

Revision ID: 3ab50abc99da
Revises: 26c01f2c7811
Create Date: 2020-03-06 12:07:57.665630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ab50abc99da'
down_revision = '26c01f2c7811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('makeTime', sa.DateTime(), nullable=True))
    op.drop_column('data', 'makeTiem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('makeTiem', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('data', 'makeTime')
    # ### end Alembic commands ###
